### ISSUE TITLE
How make fluid layout... 

### ISSUE THREAD

**Issue by mynocms** [goFrendiAsgard/No-CMS#111]
Almost everything is expected from no-cms is working very smoothly.

However due to responsive theme,  the lists can not take advantage of the width available.  How to make template fluid  ( want to remove responsive theme) .  I am aware that it is do with the css file.  But unfortunately I could not locate exact file and line number.

Any help in this is appreciated.

Regards,

**Comment by goFrendiAsgard** [comment]
You can modify the layout of your theme. It is located at `themes/neutral/views/layouts`.
Change this part:
```php
<?php
            echo $template['css'];
            $asset = new CMS_Asset();
            if($__is_bootstrap_cdn_connected){
                $asset->add_css('//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css');
            }else{  
                $asset->add_cms_css('bootstrap/css/bootstrap.min.css');
            }
            $asset->add_themes_css('bootstrap.min.css', '{{ used_theme }}', 'default');
            $asset->add_themes_css('style.css', '{{ used_theme }}', 'default');
            echo $asset->compile_css();
        ?>
```

Add your additional css after this line, follow this guide:
    http://getbootstrap.com/examples/non-responsive/
