### ISSUE TITLE
Performance Issue

### ISSUE THREAD

**Issue by ibnoe** [goFrendiAsgard/No-CMS#112]
lastest no-cms running slowly on my computer.. when i see the profiler.
there are  192  QUERIES on default installation.
when we see the queries, there are many similar query

**Comment by ibnoe** [comment]
lastest no-cms running slowly on my computer.. when i see the profiler.
there are  192 QUERIES on default installation.
when we see the queries, there are many similar query

**Comment by goFrendiAsgard** [comment]
How do you see the queries?

**Comment by heruprambadi** [comment]
just add $this->output->enable_profiler(1) on your cms_controller (ibnoe)

**Comment by goFrendiAsgard** [comment]
Thank you. I'll inspect further.

On Wed, Mar 18, 2015 at 4:46 PM, heruprambadi <notifications@github.com>
wrote:

> just add $this->output->enable_profiler(1) on your cms_controller (ibnoe)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/goFrendiAsgard/No-CMS/issues/112#issuecomment-82855196>
> .
>



-- 

-------------------------------------------------------------------------------------------------
Go Frendi Gunawan.

**Comment by goFrendiAsgard** [comment]
Still trying to reduce the query.
![screenshot from 2015-03-19 21 13 57](https://cloud.githubusercontent.com/assets/883662/6732219/e465912a-ce7c-11e4-9e9d-cf4a8d761a4c.png)

**Comment by goFrendiAsgard** [comment]
Okay, it is now only 45 queries. I know use static properties to cache some query result such as widget and navigation.
