### ISSUE TITLE
XSS filtering

### ISSUE THREAD

**Issue by kampar** [goFrendiAsgard/No-CMS#114]
when I try to playing around with contact_us module, I think it will be good if there are some mechanism to filter out XSS or any dangerous HTML tag before inserting it (the $content) into database

this is my quick_and_dirty change on line 69 /modules/contact_us/controllers/contact_us.php
```php
$data['content'] = htmlentities($content);//<script>while(1)alert(1);</script>
```

**Comment by goFrendiAsgard** [comment]
Thank you. Gonna merge it soon
