### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by Domeman** [goFrendiAsgard/No-CMS#116]
After install still at the install screen.
How do you get to the main menu?

Sometimes the database didn't create all the tables, blog tables

**Comment by goFrendiAsgard** [comment]
Is there any error in application/logs?

**Comment by Domeman** [comment]
No, I am new to codeiginiter. I can get the install to work. I end up back at the install screen.
I am using the Abyss web server. http://www.aprelium.com/abyssws/

What should the directory structure look like?

**Comment by goFrendiAsgard** [comment]
Well, probably it is because of htaccess problem.
Abyss Server doesn't have any support to htaccess. Thus some features will not work at all, i.e: multisite.

No-CMS is designed for apache web server.
However if you want to just use the basic functionality, you can try to install without "hide index" option checked.

**Comment by Domeman** [comment]
Thank you for your help, Abyss web server is very robust. Its blocks access by setting permissions
in the server for access.

Getting the following error now when trying to install the development version
Fatal error: require_once(): Failed opening required 'G:\Abyss Web Server\no_cms\application/config/constants.php' (include_path='.;C:\php\pear') in G:\Abyss Web Server\no_cms\system\core\CodeIgniter.php on line 70

This looks good 
  www or htdocs
   |--- index.php
   |--- application - placed one level up from htdocs these are then protected
   |--- system - placed one level up from htdocs these are then protected
   |--- (etc) - placed one level up from htdocs these are then protected

**Comment by goFrendiAsgard** [comment]
Is the file exists? G:\Abyss Web Server\no_cms\application/config/constants.php

**Comment by Domeman** [comment]
Its in config\first-time, which looks correct

**Comment by goFrendiAsgard** [comment]
There should also be another outside config\first-time
Try to make `config\constants.php` : 
```php
<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

```

**Comment by Domeman** [comment]
Missing no_cms\application/core/MY_CodeIgniter.php

**Comment by goFrendiAsgard** [comment]
Are you sure you use the newest development version?

On Tue, Apr 7, 2015 at 8:11 PM, Roger <notifications@github.com> wrote:

> Missing no_cms\application/core/MY_CodeIgniter.php
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/goFrendiAsgard/No-CMS/issues/116#issuecomment-90544121>
> .
>



-- 

-------------------------------------------------------------------------------------------------
Go Frendi Gunawan.

**Comment by Domeman** [comment]
Installs and ends back at the install screen

**Comment by goFrendiAsgard** [comment]
Sorry, but I think you should try with apache.

**Comment by anmoljain9** [comment]
actully i am try to install no-cms and  have install xampp on windows 8
when i am installing no-cms it showing that type of error 
![no-cms](https://cloud.githubusercontent.com/assets/14113485/9665533/9985b356-528e-11e5-9d4d-00045db0c478.png)
how can i come frm this

**Comment by goFrendiAsgard** [comment]
Please open up task manager, do you have enough RAM?
I mean you might have a lot of programs run on startup.

Also, please ensure that mysql is already running as well.
