### ISSUE TITLE
Blocker will not install

### ISSUE THREAD

**Issue by alwin4711** [goFrendiAsgard/No-CMS#118]
In both Versions master and devolepment i got errors when i try to activate them...
Master:
Error Number: 1406
Data too long for column 'content' at row 1
INSERT INTO `cms_block_ip` (`id_label`, `content`) VALUES (5, '1.0.1.0/24 1.0.......

on development:

Error Number: 1064

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'not set'',''black list'',''white list'') NULL, CONSTRAINT `pk_cms_block_label` ' at line 4

CREATE TABLE `cms_block_label` ( `id` INT(20) UNSIGNED NOT NULL AUTO_INCREMENT, `name` varchar(45) NULL, `status` enum(''not set'',''black list'',''white list'') NULL, CONSTRAINT `pk_cms_block_label` PRIMARY KEY(`id`) ) DEFAULT CHARACTER SET = utf8 COLLATE = utf8_general_ci

Filename: C:/xampp/htdocs/no-cms/modules/blocker/controllers/Info.php

Line Number: 114

Any idea ?
Best regards
Alain

**Comment by goFrendiAsgard** [comment]
Hi Alain, Thx for your report. I will inspect this further and inform you tomorrow or day after tomorrow.

**Comment by alwin4711** [comment]
Thank You,
i still try to use your no-cms but i'm not so close to ci.
I'm old but i will learn ;-)
Ic will try  the 'contact us' as an example to start and make it multilingual..
cu

**Comment by goFrendiAsgard** [comment]
Well, I appreciate your help on spotting the errors on No-CMS.
Just let me know if you have something to ask.

**Comment by alwin4711** [comment]
I'm not sure if the pull request ist done or not ??? 
Sorry..

**Comment by alwin4711** [comment]
next try with the master branche
Error Number: 1406

Data too long for column 'content' at row 1

INSERT INTO `cms_block_ip` (`id_label`, `content`) VALUES (5, '1.0.1.0/24 1.0.2.0/23 1.0.8.0/21 1.0.32.0/19 1.1.0.0/24 1.1.2.0/23 1.1.4.0/22 1.1.8.0/21 1.1.16.0/20 1.1.32.0/19 1.2.0.0/23 1.2.2.0/24 1.2.4.0/22 1.2.8.0/21 1.2.16.0/20 1.2.32.0/19 1.2.64.0/18 1.3.0.0/16 1.4.1.0/24 1.4.2.0/23 1.4.4.0/22 1.4.8.0/21 1.4.16.0/20 1.4.32.0/19 1.4.64.0/18 1.8.0.0/16

**Comment by alwin4711** [comment]
ok, now it is working
Thank you
