### ISSUE TITLE
Database error, Modulgenerator

### ISSUE THREAD

**Issue by alwin4711** [goFrendiAsgard/No-CMS#121]
If i make a new modul with database and i try to use the Manage xxx button i got a....

The table exist and is accessible via phpmyadmin
If i put a print $this->basic_db_table in the File C:\xampp\htdocs\no-cms\application\libraries\Grocery_crud.php file near by Line Number: 4725
I will see the correct tablename, for example cms_alwin_2_notizen

--------------------------------------------
Type: Exception

Message: The table name does not exist. Please check you database and try again.

Filename: C:\xampp\htdocs\no-cms\application\libraries\Grocery_crud.php

Line Number: 4725

Backtrace:

File: C:\xampp\htdocs\no-cms\application\libraries\Grocery_crud.php
Line: 4233
Function: get_table

File: C:\xampp\htdocs\no-cms\application\libraries\Grocery_crud.php
Line: 4249
Function: pre_render

File: C:\xampp\htdocs\no-cms\application\libraries\Extended_grocery_crud.php
Line: 1532
Function: render

File: C:\xampp\htdocs\no-cms\modules\alwin_2\controllers\Manage_notizen.php
Line: 191
Function: render

File: C:\xampp\htdocs\no-cms\index.php
Line: 455
Function: require_once

**Comment by goFrendiAsgard** [comment]
Is there any sql error?

**Comment by alwin4711** [comment]
No Sir....;-)
-- phpMyAdmin SQL Dump
-- version 4.4.2
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Erstellungszeit: 23. Apr 2015 um 14:00
-- Server-Version: 5.6.24-log
-- PHP-Version: 5.6.3

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Datenbank: `no_cms`
--

-- --------------------------------------------------------

--
-- Tabellenstruktur für Tabelle `cms_alwin_2_notizen`
--

CREATE TABLE IF NOT EXISTS `cms_alwin_2_notizen` (
  `id` int(20) unsigned NOT NULL,
  `Text` mediumtext,
  `create_time` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Indizes der exportierten Tabellen
--

--
-- Indizes für die Tabelle `cms_alwin_2_notizen`
--
ALTER TABLE `cms_alwin_2_notizen`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT für exportierte Tabellen
--

--
-- AUTO_INCREMENT für Tabelle `cms_alwin_2_notizen`
--
ALTER TABLE `cms_alwin_2_notizen`
  MODIFY `id` int(20) unsigned NOT NULL AUTO_INCREMENT;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;

**Comment by goFrendiAsgard** [comment]
Can you please send me the generated module? I'm now working on development
version, so things might be different.

On Thu, Apr 23, 2015 at 7:01 PM, Alain Lasserre <notifications@github.com>
wrote:

> No Sir....;-)
> -- phpMyAdmin SQL Dump
> -- version 4.4.2
> -- http://www.phpmyadmin.net
>
> -- Host: localhost
> -- Erstellungszeit: 23. Apr 2015 um 14:00
> -- Server-Version: 5.6.24-log
> -- PHP-Version: 5.6.3
>
> SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
> SET time_zone = "+00:00";
>
> /
> *!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */; /*!40101
> SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS
> */; /*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION
> */; /*!40101 SET NAMES utf8 */;
>  -- Datenbank: no_cms
> ------------------------------
>  -- Tabellenstruktur für Tabelle cms_alwin_2_notizen
>
> CREATE TABLE IF NOT EXISTS cms_alwin_2_notizen (
> id int(20) unsigned NOT NULL,
> Text mediumtext,
> create_time datetime DEFAULT NULL
> ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
>  -- Indizes der exportierten Tabellen -- Indizes für die Tabelle
> cms_alwin_2_notizen
>
> ALTER TABLE cms_alwin_2_notizen
> ADD PRIMARY KEY (id);
>  -- AUTO_INCREMENT für exportierte Tabellen -- AUTO_INCREMENT für Tabelle
> cms_alwin_2_notizen
>
> ALTER TABLE cms_alwin_2_notizen
> MODIFY id int(20) unsigned NOT NULL AUTO_INCREMENT;
> /
> *!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */; /*!40101
> SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS
> */; /*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/goFrendiAsgard/No-CMS/issues/121#issuecomment-95560069>
> .
>



-- 

-------------------------------------------------------------------------------------------------
Go Frendi Gunawan.

**Comment by alwin4711** [comment]
send by email

**Comment by goFrendiAsgard** [comment]
This one should work: https://github.com/goFrendiAsgard/No-CMS/tree/e22d789048fe5105a85187cbaa5ae30500980e25
Please re-open the issue or make a new one if you find problem with this.
