### ISSUE TITLE
Modulgenerator language support

### ISSUE THREAD

**Issue by alwin4711** [goFrendiAsgard/No-CMS#122]
How does the modulgenerator helps me to implement a multilingual modul ?
I saw the asset/language folder.
Is he  supporting then language system? for example: in the form the database label caption text ?
CIao
Alain

**Comment by goFrendiAsgard** [comment]
Yes, it should be.

On Thu, Apr 23, 2015 at 7:44 PM, Alain Lasserre <notifications@github.com>
wrote:

> How does the modulgenerator helps me to implement a multilingual modul ?
> I saw the asset/language folder.
> Is he supporting then language system? for example: in the form the
> database label caption text ?
> CIao
> Alain
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/goFrendiAsgard/No-CMS/issues/122>.
>



-- 

-------------------------------------------------------------------------------------------------
Go Frendi Gunawan.
