### ISSUE TITLE
Installer error ? database

### ISSUE THREAD

**Issue by alwin4711** [goFrendiAsgard/No-CMS#123]
Hi Frendi,
when i install no-cms with schema 'no-cms' and next time i install no-cms-master with schema 'no-cms-master' the installer will erase the first database no-cms and makes the no-cms-master.

So he is deleteing the wrong database.
I want to use both installations.
All that happens under Win7 and xampp
Ciao
Alain

**Comment by goFrendiAsgard** [comment]
I'm still inspecting your database. It is 149 tables. I never thought there
will be someone importing that large amount of tables.
However, I'm currently focus on development version. So, my first priority
is to make the development version works.

On Sun, Apr 26, 2015 at 10:22 PM, Alain Lasserre <notifications@github.com>
wrote:

> Hi Frendi,
> when i install no-cms with schema 'no-cms' and next time i install
> no-cms-master with schema 'no-cms-master' the installer will erase the
> first database no-cms and makes the no-cms-master.
>
> So he is deleteing the wrong database.
> I want to use both installations.
> All that happens under Win7 and xampp
> Ciao
> Alain
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/goFrendiAsgard/No-CMS/issues/123>.
>



-- 

-------------------------------------------------------------------------------------------------
Go Frendi Gunawan.

**Comment by alwin4711** [comment]
Hi Frendi,

i told you it is a stress test ;-))

I will never use it in real.

But the install error was not with this database.

If you like to use both branches like:
http://localhost/no-cms-master
with schema/database 'no-cms-master' and

http://localhost/no-cms-development
with schema/database 'no-cms'

and you install it with the install funktion
then the second installation will erase the first database 'no-cms-master'.


So after the 2 installations you have only 1 database (from the the last 
installation) on the database server.






Am 28.04.2015 um 05:26 schrieb Go Frendi Gunawan:

**Comment by goFrendiAsgard** [comment]
Oh, I'm really sorry. I misunderstand it. Okay, I'll try to install both of
them side by side

On Tue, Apr 28, 2015 at 2:28 PM, Alain Lasserre <notifications@github.com>
wrote:

> Hi Frendi,
>
> i told you it is a stress test ;-))
>
> I will never use it in real.
>
> But the install error was not with this database.
>
> If you like to use both branches like:
> http://localhost/no-cms-master
> with schema/database 'no-cms-master' and
>
> http://localhost/no-cms-development
> with schema/database 'no-cms'
>
> and you install it with the install funktion
> then the second installation will erase the first database 'no-cms-master'.
>
>
> So after the 2 installations you have only 1 database (from the the last
> installation) on the database server.
>
>
>
>
>
>
> Am 28.04.2015 um 05:26 schrieb Go Frendi Gunawan:
> > I'm still inspecting your database. It is 149 tables. I never thought
> > there
> > will be someone importing that large amount of tables.
> > However, I'm currently focus on development version. So, my first
> priority
> > is to make the development version works.
> >
> > On Sun, Apr 26, 2015 at 10:22 PM, Alain Lasserre
> > <notifications@github.com>
> > wrote:
> >
> > > Hi Frendi,
> > > when i install no-cms with schema 'no-cms' and next time i install
> > > no-cms-master with schema 'no-cms-master' the installer will erase the
> > > first database no-cms and makes the no-cms-master.
> > >
> > > So he is deleteing the wrong database.
> > > I want to use both installations.
> > > All that happens under Win7 and xampp
> > > Ciao
> > > Alain
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/goFrendiAsgard/No-CMS/issues/123>.
> > >
> >
> >
> >
> > --
> >
> >
> -------------------------------------------------------------------------------------------------
> > Go Frendi Gunawan.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/goFrendiAsgard/No-CMS/issues/123#issuecomment-96895788
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/goFrendiAsgard/No-CMS/issues/123#issuecomment-96958652>
> .
>



-- 

-------------------------------------------------------------------------------------------------
Go Frendi Gunawan.

**Comment by goFrendiAsgard** [comment]
Hi Alain, this version should works. Please try
https://github.com/goFrendiAsgard/No-CMS/tree/12fe5b607ef81c51e66b5cee8aa2237e17969254

**Comment by alwin4711** [comment]
Thank you

**Comment by alwin4711** [comment]
Hi Frendi,
is this Version a stable or a development package ?
I got still the same problem

i install no-cms-master with "no-cms-master" schema and than no-cms-development with "no-cms-dev" schema.
second installtions kills the first schema.
Cu Alain

**Comment by goFrendiAsgard** [comment]
Both version should be okay. By kills the first schema do you mean that the
tables are overridden?

On Mon, May 4, 2015 at 11:05 PM, Alain Lasserre <notifications@github.com>
wrote:

> Hi Frendi,
> is this Version a stable or a development package ?
> I got still the same problem
>
> i install no-cms-master with "no-cms-master" schema and than
> no-cms-development with "no-cms-dev" schema.
> second installtions kills the first schema.
> Cu Alain
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/goFrendiAsgard/No-CMS/issues/123#issuecomment-98766920>
> .
>



-- 

-------------------------------------------------------------------------------------------------
Go Frendi Gunawan.

**Comment by alwin4711** [comment]
No
for example: the first installation schema name is no-cms-master and the second schema is no-cms-dev
after second installaton the no-cms-master database ist complete deleted , only the second schema exist.
It look like the installaion is searching for some schema like no-cms* and deletes it befor installation

**Comment by goFrendiAsgard** [comment]
Really? I try with xampp yesterday. I think the problem is because both of
them has the same cookie name.
I'll check it again by using my virtual machine.
Can you please try to use different browser (e.g: use google chrome to
install the master, and use firefox to install the development)?

On Wed, May 6, 2015 at 4:26 AM, Alain Lasserre <notifications@github.com>
wrote:

> No
> for example: the first installation schema name is no-cms-master and the
> second schema is no-cms-dev
> after second installaton the no-cms-master database ist complete deleted ,
> only the second schema exist.
> It look like the installaion is searching for some schema like no-cms* and
> deletes it befor installation
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/goFrendiAsgard/No-CMS/issues/123#issuecomment-99227625>
> .
>



-- 

-------------------------------------------------------------------------------------------------
Go Frendi Gunawan.

**Comment by alwin4711** [comment]
ok ;-)
it was the session cookie.
I use different browsers and then it works.
But any way to change this or maybe put some information in the doc for users like me ;-)
Thank you Frendi

**Comment by goFrendiAsgard** [comment]
Very good. This commit fix up everything: https://github.com/goFrendiAsgard/No-CMS/tree/e22d789048fe5105a85187cbaa5ae30500980e25
