### ISSUE TITLE
Using database outside no-cms schema

### ISSUE THREAD

**Issue by alwin4711** [goFrendiAsgard/No-CMS#124]
Hi Frendi,
when i use the modulgenarator the importet schema is inserted to the default no-cms schema /database.
How can i tell the Modulgenerator to use a database outside the no-cms data schema.
For example i have 2 or more installations of nocms and i like to use for all the same database.

Ciao
Alain

**Comment by goFrendiAsgard** [comment]
Hi Alain,
You cannot do that easily. No-CMS is designed to only work with one database.
If you want to have several installation with the same database, you can use multisite. Good luck

**Comment by alwin4711** [comment]
ok,
thank you
I will try that
