### ISSUE TITLE
Firefox crash 

### ISSUE THREAD

**Issue by alwin4711** [goFrendiAsgard/No-CMS#125]
Hi Frendi,
after installing the latest branch firefox will crash ;-))
I use Win 7-64 and firefox 37.0.2
No problem with Chrome
CIao
Alain

**Comment by goFrendiAsgard** [comment]
Hmm. I can't test this. Do you  experience crash after the second trial too?

**Comment by alwin4711** [comment]
yes, i think it depends on some of my firefox addons.
When i switsch all off it works fine.
I send the crashreport to mozilla.
we will see what is happen.
cu
Alain

**Comment by goFrendiAsgard** [comment]
I see. Some firefox plugins have conflict with javascript.
