### ISSUE TITLE
Bugs when add new article

### ISSUE THREAD

**Issue by hafiz123** [goFrendiAsgard/No-CMS#132]
Hi Frendi..

found 1 bugs when add new article. the photos was uploaded to the table blog photo but the article id is inserted 0.edit is working fine, just in add article only.

ps:i did email u also..just post here in case anyone other face the same issues

**Comment by goFrendiAsgard** [comment]
Still have problem with the new version?

**Comment by goFrendiAsgard** [comment]
Re open if issue still persist
