### ISSUE TITLE
LDAP authentication

### ISSUE THREAD

**Issue by ohnague** [goFrendiAsgard/No-CMS#134]
Good Morning
There is some method to be able to have an LDAP authentication in non-cms

or if any library and how to implement or carry this non-cms

I think it's a good idea

greetings from Cuba

Note: You could look at this question
https://github.com/goFrendiAsgard/No-CMS/issues/133

**Comment by goFrendiAsgard** [comment]
You can override No-CMS/application/helpers/cms_extended_login_helper.php to recognize LDAP. Use this as reference: https://github.com/goFrendiAsgard/No-CMS/blob/master/doc/tutorial/programmer_extended_login.md

This might works: Hi. First you need this: https://www.exchangecore.com/blog/how-use-ldap-active-directory-authentication-php/ (I never try it by myself)
