### ISSUE TITLE
MySQL server has gone away

### ISSUE THREAD

**Issue by heruprambadi** [goFrendiAsgard/No-CMS#136]
i'm not sure if it is bug or not. But when i tested nocms online, this error message appears so often. Is it my server problem or nocms ?
![capture](https://cloud.githubusercontent.com/assets/5396455/10316946/1aaca32e-6c8c-11e5-95ee-280042136a4e.JPG)

**Comment by goFrendiAsgard** [comment]
I think it is your server problem. It means that the connection to mysql has been cut off several time.

**Comment by heruprambadi** [comment]
Make sense. I've never experience this on localhost and the other online hosting.
