### ISSUE TITLE
updating page content error

### ISSUE THREAD

**Issue by ShiroGaijin** [goFrendiAsgard/No-CMS#140]
when using the editor to update a page clicking the save icon causes an unexpected error.

Complete Page source:
{"success":true,"insert_primary_key":true,"success_message":"&lt;p&gt;Your data has been successfully updated. &lt;a href='http://welshwebwizardry.co.uk/main/navigation'&gt;Go back to list&lt;/a&gt;&lt;/p&gt;","success_list_url":"http://welshwebwizardry.co.uk/main/navigation/success/19"}

**Comment by goFrendiAsgard** [comment]
Is the error always occur?

**Comment by ShiroGaijin** [comment]
yes, It's when using the save icon on the editor to update a navigation page.

**Comment by goFrendiAsgard** [comment]
I can't reproduce the error. Can you please try again with the newest version from github?
Also, if you are familiar with chrome or firefox developer tools, please press ctrl + i before updating the content. See the console tab. You might find some error messages there (probably related to browser compatibility).

I can say that the page was actually updated (see from your "error" message).

**Comment by ShiroGaijin** [comment]
after a new install of the latest one from here, it still gives an error, I'm using firefox and after installing I update the main_index page by clicking the save icon in the static content box, not by scrolling down and clicking an update button.

**Comment by goFrendiAsgard** [comment]
This is not the correct way. You should scroll down and click save.
Is that one work?

**Comment by goFrendiAsgard** [comment]
Try with this one: https://github.com/goFrendiAsgard/No-CMS/tree/a874ffefc58ba538a2daf05129e07db5d5bde8ad

Don't forget to press ctrl + F5 to reload javascript & css
