### ISSUE TITLE
View issue on mobile

### ISSUE THREAD

**Issue by witwall** [goFrendiAsgard/No-CMS#146]
The same page on the mobile(5.5"), LANDSCAPE vs PORTRAIT. using the default theme

![screenshot_2016-01-08-12-37-47-412](https://cloud.githubusercontent.com/assets/3222056/12190592/30445b9c-b605-11e5-81e5-13b876270b02.png)

![screenshot_2016-01-08-12-37-41-35](https://cloud.githubusercontent.com/assets/3222056/12190599/41cf13e8-b605-11e5-8d87-85c09fcb96bf.png)

**Comment by goFrendiAsgard** [comment]
Fixed, you can re-download the new version, or simply add several lines in `assets/grocery_crud/themes/no-flexigrid/css/flexigrid.css`

https://github.com/goFrendiAsgard/No-CMS/commit/094e0785e65bd1ddc91d900f381719d6dabbd659

Thank you for the report BTW :+1:
