### ISSUE TITLE
enum or another table(foreign-key), which is better?

### ISSUE THREAD

**Issue by witwall** [goFrendiAsgard/No-CMS#148]
for example, I have 18 brands to manager, I can set brand as enum. but one day, I want to add some brands or set some brands as disable, another table will be better. 

if use foreign-key, there will be another [issue 147](https://github.com/goFrendiAsgard/No-CMS/issues/147) I met before.
of course I save another unique id, not key column in the product table(who has a column brand).
and enum seems is not a good choice.

**Comment by goFrendiAsgard** [comment]
Foreign key is better.
