### ISSUE TITLE
how to get the current navigation id in current template folder?

### ISSUE THREAD

**Issue by redsh4re** [goFrendiAsgard/No-CMS#152]

**Comment by goFrendiAsgard** [comment]
Sorry. What do you mean by current template folder?
And why do you need to get current navigation id?

**Comment by redsh4re** [comment]
Yes. To get some additional settings of current navigation id

**Comment by goFrendiAsgard** [comment]
To get the navigation name, you can use this:

```php
$navigation_name = $this->cms_navigation_name();
```
This will return the current navigation name by matching the url with the available navigation list. You can get navigation_id etc by accessing the database. (i.e: SELECT FROM cms_main_navigation)

```php
$this->db->select('*')->from(cms_table_name('main_navigation')->where('navigation_name', $navigation_name);
```

**Comment by redsh4re** [comment]
Thanks
