### ISSUE TITLE
git clone command in user documentation failed

### ISSUE THREAD

**Issue by sfthurber** [goFrendiAsgard/No-CMS#154]
C:\Users\User>git clone git@github.com:goFrendiAsgard/No-CMS.git
Cloning into 'No-CMS'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

C:\Users\User>

this command did work:
C:\Users\User>git clone https://github.com/goFrendiAsgard/No-CMS.git
Cloning into 'No-CMS'...
remote: Counting objects: 26324, done.
remote: Total 26324 (delta 0), reused 0 (delta 0), pack-reused 26324 eceiving objects: 100% (26324/26324), 56.17 MiB | 1Receiving objects: 100% (26324/26324), 56.36 MiB | 1.02 MiB/s, done.

Resolving deltas: 100% (14261/14261), done.
Checking connectivity... done.
Checking out files: 100% (3022/3022), done.

C:\Users\User>

**Comment by goFrendiAsgard** [comment]
Okay thx, gonna add this to documentation
