### ISSUE TITLE
 Third Party Authentication don´t work

### ISSUE THREAD

**Issue by allado** [goFrendiAsgard/No-CMS#157]
Hi

I love no-cms, i use it

But i ´ve problem with hibrydauth, login with facebook... it does not work

In the table "cms_main_user" appear the user with "auth_facebook" and "user_id" completed... but "user_name" and "email" fields ar empty.

I tried new installations on different servers but nowhere I run facebook login.

you can helpme ?

Best regards

**Comment by goFrendiAsgard** [comment]
Sorry, forget to inform you. I've already resolve this by updating hybridauth

**Comment by allado** [comment]
Thank You !!!

Good Job !!!
