### ISSUE TITLE
how to disable third party auth ?

### ISSUE THREAD

**Issue by knulle** [goFrendiAsgard/No-CMS#162]
is it possible to completely disable that feature ? 
Although I disabled all login types in cms-management => setting => third party auth it's still contained within the main menu.

**Comment by Tpojka** [comment]
In [config file](https://github.com/goFrendiAsgard/No-CMS/blob/master/application/third_party/hybridauth/config.php) disable or set `FALSE` to enabled for those you don't need.

**Comment by knulle** [comment]
Thanks!
Ok, I tried
 return FALSE
 return array()
but the Navigation entry still remained.
Now I simply set the navigation-entry to "inactive" via the menu CMS-administration => navigation
