### ISSUE TITLE
jquery fancybox

### ISSUE THREAD

**Issue by orazionelson** [goFrendiAsgard/No-CMS#164]
The  jquery.fancybox called in grocerycrud in last master version doesn't show the close button, and there are no relevant messages in console.
![schermata da 2016-06-19 02 16 35](https://cloud.githubusercontent.com/assets/113308/16174492/ff9a7a32-35c3-11e6-8615-e32ba4413824.png)

In the edit mode is the same.

**Comment by orazionelson** [comment]
I found a patch on this page:
https://github.com/nvidoni/fancybox/issues/2

> This fix worked for me at line 570:
//content.get(0).style.removeAttribute('filter');
//wrap.get(0).style.removeAttribute('filter');
$('#fancybox-content').css('filter', 0);
$('#fancybox-wrap').css('filter', 0);

**Comment by goFrendiAsgard** [comment]
Fixed. Thank you very much
https://github.com/goFrendiAsgard/No-CMS/commit/faebc715dab4d36d44ffc8619f41c59d5d3d7368
