### ISSUE TITLE
Error running NO-CMS on xampp installation

### ISSUE THREAD

**Issue by imerljak** [goFrendiAsgard/No-CMS#166]
i have tried running it on a xampp server and it shows me this error whenever I try to load the url.

`Parse error: syntax error, unexpected '<<' (T_SL) in /opt/lampp/htdocs/Projetos/noCMS/index.php on line 315`

PHP Version is 5.6.23.

CMS is under `localhost/projects/noCMS/`

**Comment by goFrendiAsgard** [comment]
Hi, try this: https://github.com/goFrendiAsgard/No-CMS/tree/4c2152722f50bc52016b352acb457c415825a4ab

**Comment by imerljak** [comment]
Great, it works :)
Thank you!
