### ISSUE TITLE
Callback in set_rules not working in HMVC

### ISSUE THREAD

**Issue by velsankar** [goFrendiAsgard/No-CMS#72]
I am getting the error message "Unable to access an error message corresponding to your field name" when I set a custom validation rule using a callback in grocery crud's set_rules method.  I widely read that this is a known problem with HMVC.  The solutions given have not worked for me.  

Code snippet:
class Manage_Departments extends CMS_Priv_Strict_Controller {

```
protected $URL_MAP = array();

public function index()
    {
         .....
         $crud->set_rules('department_name','Department','callback_unique_check');
         ......
    }

   public function unique_check()
   {
         // for testing i removed the actual lines in this method and tried returning true/false and get the same above mentioned error message for both.
          return FALSE;
    }
```

}

Did anyone come across this while using No-CMS?

Could anyone help me out on this?

**Comment by heruprambadi** [comment]
i got the same error message too. Bug again ?

**Comment by 1nv4d3r5** [comment]
http://www.mahbubblog.com/php/form-validation-callbacks-in-hmvc-in-codeigniter/ 
This one worked for me.
